sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=davlloyd/dispatch-events-vcenter
    
before_script:
  - docker pull "$IMAGE_NAME" || true

script:
  - docker build --pull --cache-from "$IMAGE_NAME" -t "$IMAGE_NAME" . 

after_script:
  - docker images

after_success:
   - sh .travis/deploy_dockerhub.sh
